spring:
  datasource:
    url: jdbc:mysql://bygojlnwzmygqjzpl6ys-mysql.services.clever-cloud.com:3306/bygojlnwzmygqjzpl6ys
    username: uinadrmdzeeg74pv
    password: PRAlXZmLULI7hIVpZhxF
  jpa:
    hibernate:
      ddl-auto: update